language: java
install: true

matrix:
    fast_finish: true
env:
    - CMD=first 
    - CMD=second    
    - CMD=third
    - CMD=fourth
    
script: travis_wait 300 python ./CI/CI-client.py $TRAVIS_COMMIT $CMD

jdk:
  - oraclejdk8