// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.test.integration;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>Test_save_window</b><br>
 * Generated     : <b>2016/07/03 7:57:07 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since  July 03, 2016
 * @author lta
 */
public abstract class Test_save_windowHelper extends RationalTestScript
{
	/**
	 * NewVersionAvailable: with default state.
	 *		.captionText : New Version Available
	 * 		.class : javax.swing.JDialog
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject _topLevelTestObject() 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("_topLevelTestObject"));
	}
	/**
	 * NewVersionAvailable: with specific test context and state.
	 *		.captionText : New Version Available
	 * 		.class : javax.swing.JDialog
	 * 		.processName : java.exe
	 */
	protected TopLevelTestObject _topLevelTestObject(TestObject anchor, long flags) 
	{
		return new TopLevelTestObject(
                        getMappedTestObject("_topLevelTestObject"), anchor, flags);
	}
	
	/**
	 * CWindowsSystem32CmdExe: with default state.
	 *		.text : C:\Windows\system32\cmd.exe
	 * 		.class : ConsoleWindowClass
	 * 		.processName : cmd.exe
	 * 		.name : C:\Windows\system32\cmd.exe
	 */
	protected TopLevelSubitemTestObject cWindowsSystem32CmdExewindow() 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("cWindowsSystem32CmdExewindow"));
	}
	/**
	 * CWindowsSystem32CmdExe: with specific test context and state.
	 *		.text : C:\Windows\system32\cmd.exe
	 * 		.class : ConsoleWindowClass
	 * 		.processName : cmd.exe
	 * 		.name : C:\Windows\system32\cmd.exe
	 */
	protected TopLevelSubitemTestObject cWindowsSystem32CmdExewindow(TestObject anchor, long flags) 
	{
		return new TopLevelSubitemTestObject(
                        getMappedTestObject("cWindowsSystem32CmdExewindow"), anchor, flags);
	}
	
	/**
	 * Locate and return the verification point CWindowsSystem32CmdExe_text object in the SUT.
	 */
	protected IFtVerificationPoint CWindowsSystem32CmdExe_textVP() 
	{
		return vp("CWindowsSystem32CmdExe_text");
	}
	protected IFtVerificationPoint CWindowsSystem32CmdExe_textVP(TestObject anchor)
	{
		return vp("CWindowsSystem32CmdExe_text", anchor);
	}
	
	

	protected Test_save_windowHelper()
	{
		setScriptName("test.integration.Test_save_window");
	}
	
}

