// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package resources.usi;

import com.rational.test.ft.object.interfaces.*;
import com.rational.test.ft.object.interfaces.SAP.*;
import com.rational.test.ft.object.interfaces.WPF.*;
import com.rational.test.ft.object.interfaces.siebel.*;
import com.rational.test.ft.object.interfaces.flex.*;
import com.rational.test.ft.object.interfaces.dojo.*;
import com.rational.test.ft.object.interfaces.generichtmlsubdomain.*;
import com.rational.test.ft.script.*;
import com.rational.test.ft.vp.IFtVerificationPoint;
import com.ibm.rational.test.ft.object.interfaces.sapwebportal.*;
/**
 * Script Name   : <b>RipperMain</b><br>
 * Generated     : <b>2016/09/19 4:34:52 AM</b><br>
 * Description   : Helper class for script<br>
 * Original Host : Windows 7 amd64 6.1 <br>
 * 
 * @since  September 19, 2016
 * @author usi
 */
public abstract class RipperMainHelper extends RationalTestScript
{
	/**
	 * MyAccounts: with default state.
	 *		tabCount : 3
	 * 		.class : javax.swing.JTabbedPane
	 * 		accessibleContext.accessibleName : My Accounts
	 * 		.tabs : {My Accounts,My Budget,My Reports}
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject _guiSubitemTestObject() 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("_guiSubitemTestObject"));
	}
	/**
	 * MyAccounts: with specific test context and state.
	 *		tabCount : 3
	 * 		.class : javax.swing.JTabbedPane
	 * 		accessibleContext.accessibleName : My Accounts
	 * 		.tabs : {My Accounts,My Budget,My Reports}
	 * 		.classIndex : 0
	 */
	protected GuiSubitemTestObject _guiSubitemTestObject(TestObject anchor, long flags) 
	{
		return new GuiSubitemTestObject(
                        getMappedTestObject("_guiSubitemTestObject"), anchor, flags);
	}
	
	

	protected RipperMainHelper()
	{
		setScriptName("usi.RipperMain");
	}
	
}

