// DO NOT EDIT: This file is automatically generated.
//
// Only the associated template file should be edited directly.
// Helper class files are automatically regenerated from the template
// files at various times, including record actions and test object
// insertion actions.  Any changes made directly to a helper class
// file will be lost when automatically updated.

package test.integration;

import com.rational.test.ft.script.RationalTestScript;

/**
 * Script Name : <b>Test_save_window</b><br>
 * Generated : <b>2016/07/02 8:24:45 AM</b><br>
 * Description : Helper class for script<br>
 * Original Host : Windows 7 x86 6.1 <br>
 * 
 * @since July 02, 2016
 * @author lta
 */
public abstract class Test_save_windowHelper extends RationalTestScript {

	protected Test_save_windowHelper() {

		this.setScriptName("test.integration.Test_save_window");
	}

}
